INFO | uvicorn.error | 2025-03-29 23:31:17 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-29 23:31:18 | line 477 | 127.0.0.1:62388 - "GET / HTTP/1.1" 404
INFO | uvicorn.access | 2025-03-29 23:31:20 | line 477 | 127.0.0.1:62393 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-29 23:31:20 | line 477 | 127.0.0.1:62393 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-29 23:31:30 | line 477 | 127.0.0.1:62412 - "POST /auth/register HTTP/1.1" 500
ERROR | uvicorn.error | 2025-03-29 23:31:30 | line 412 | Exception in ASGI application
Traceback (most recent call last):
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/router.py", line 20, in register
    user = await AuthService.register(db, user_data.email, user_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/service.py", line 12, in register
    result = await db.execute(select(User).filter_by(email=email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1128, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 5432, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 5432)
INFO | uvicorn.error | 2025-03-29 23:32:09 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-29 23:32:10 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-29 23:32:10 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-29 23:32:10 | line 92 | Finished server process [17767]
INFO | uvicorn.error | 2025-03-29 23:32:26 | line 62 | Application startup complete.
INFO | uvicorn.error | 2025-03-29 23:32:29 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-29 23:32:29 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-29 23:32:29 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-29 23:32:29 | line 92 | Finished server process [17852]
INFO | uvicorn.error | 2025-03-29 23:34:03 | line 62 | Application startup complete.
INFO | uvicorn.error | 2025-03-29 23:34:26 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-29 23:34:27 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-29 23:34:27 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-29 23:34:27 | line 92 | Finished server process [17934]
INFO | uvicorn.error | 2025-03-29 23:34:31 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-29 23:34:40 | line 477 | 127.0.0.1:62515 - "POST /auth/register HTTP/1.1" 500
ERROR | uvicorn.error | 2025-03-29 23:34:40 | line 412 | Exception in ASGI application
Traceback (most recent call last):
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/router.py", line 20, in register
    user = await AuthService.register(db, user_data.email, user_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/service.py", line 12, in register
    result = await db.execute(select(User).filter_by(email=email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1128, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 5432, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 5432)
INFO | uvicorn.error | 2025-03-29 23:34:48 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-29 23:34:48 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-29 23:34:48 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-29 23:34:48 | line 92 | Finished server process [17975]
INFO | uvicorn.error | 2025-03-29 23:34:50 | line 62 | Application startup complete.
INFO | uvicorn.error | 2025-03-29 23:35:00 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-29 23:35:00 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-29 23:35:00 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-29 23:35:00 | line 92 | Finished server process [18007]
INFO | uvicorn.error | 2025-03-29 23:35:44 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-29 23:35:51 | line 477 | 127.0.0.1:62577 - "POST /auth/register HTTP/1.1" 500
ERROR | uvicorn.error | 2025-03-29 23:35:51 | line 412 | Exception in ASGI application
Traceback (most recent call last):
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/router.py", line 20, in register
    user = await AuthService.register(db, user_data.email, user_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/service.py", line 12, in register
    result = await db.execute(select(User).filter_by(email=email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1128, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 5432, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 5432)
INFO | app.auth | 2025-03-29 23:36:03 | line 23 | User registered successfully: user@example.com
INFO | uvicorn.access | 2025-03-29 23:36:03 | line 477 | 127.0.0.1:62590 - "POST /auth/register HTTP/1.1" 201
INFO | uvicorn.error | 2025-03-29 23:36:46 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-29 23:36:47 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-29 23:36:47 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-29 23:36:47 | line 92 | Finished server process [18072]
INFO | uvicorn.error | 2025-03-30 10:48:32 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 10:48:38 | line 477 | 127.0.0.1:49567 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 10:48:38 | line 477 | 127.0.0.1:49567 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 10:49:22 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 10:49:22 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 10:49:22 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 10:49:22 | line 92 | Finished server process [19192]
INFO | uvicorn.error | 2025-03-30 10:49:23 | line 62 | Application startup complete.
WARNING | app.auth | 2025-03-30 10:49:31 | line 14 | Registration with existing email
INFO | uvicorn.access | 2025-03-30 10:49:31 | line 477 | 127.0.0.1:49609 - "POST /auth/register HTTP/1.1" 400
INFO | app.auth | 2025-03-30 10:49:37 | line 23 | User registered successfully: user2@example.com
INFO | uvicorn.access | 2025-03-30 10:49:37 | line 477 | 127.0.0.1:49635 - "POST /auth/register HTTP/1.1" 201
WARNING | app.auth | 2025-03-30 10:49:46 | line 14 | Registration with existing email
INFO | uvicorn.access | 2025-03-30 10:49:46 | line 477 | 127.0.0.1:49670 - "POST /auth/register HTTP/1.1" 400
INFO | uvicorn.error | 2025-03-30 10:49:58 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 10:49:58 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 10:49:58 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 10:49:58 | line 92 | Finished server process [19252]
INFO | uvicorn.error | 2025-03-30 10:50:03 | line 62 | Application startup complete.
INFO | app.auth | 2025-03-30 10:50:14 | line 23 | User registered successfully: user3@example.com
INFO | uvicorn.access | 2025-03-30 10:50:14 | line 477 | 127.0.0.1:49687 - "POST /auth/register HTTP/1.1" 201
INFO | uvicorn.error | 2025-03-30 10:50:46 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 10:50:46 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 10:50:46 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 10:50:46 | line 92 | Finished server process [19320]
INFO | uvicorn.error | 2025-03-30 10:50:46 | line 62 | Application startup complete.
INFO | uvicorn.error | 2025-03-30 10:50:48 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 10:50:48 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 10:50:48 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 10:50:48 | line 92 | Finished server process [19371]
INFO | uvicorn.error | 2025-03-30 10:50:51 | line 62 | Application startup complete.
INFO | app.auth | 2025-03-30 10:51:23 | line 23 | User registered successfully: user4@example.com
INFO | uvicorn.access | 2025-03-30 10:51:23 | line 477 | 127.0.0.1:49764 - "POST /auth/register HTTP/1.1" 201
INFO | app.auth | 2025-03-30 10:51:52 | line 36 | Success login for user@example.com
INFO | uvicorn.access | 2025-03-30 10:51:52 | line 477 | 127.0.0.1:49806 - "POST /auth/login HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 10:51:59 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 10:51:59 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 10:51:59 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 10:51:59 | line 92 | Finished server process [19397]
INFO | uvicorn.error | 2025-03-30 11:51:03 | line 62 | Application startup complete.
INFO | app.auth | 2025-03-30 11:51:28 | line 23 | User registered successfully: user5@example.com
INFO | uvicorn.access | 2025-03-30 11:51:28 | line 477 | 127.0.0.1:50802 - "POST /auth/register HTTP/1.1" 201
INFO | uvicorn.error | 2025-03-30 11:51:33 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 11:51:33 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 11:51:33 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 11:51:33 | line 92 | Finished server process [19776]
INFO | uvicorn.error | 2025-03-30 15:21:21 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 15:21:29 | line 477 | 127.0.0.1:52053 - "POST /auth/login HTTP/1.1" 500
ERROR | uvicorn.error | 2025-03-30 15:21:29 | line 412 | Exception in ASGI application
Traceback (most recent call last):
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/router.py", line 34, in login
    user = await AuthService.login(db, user_data.email, user_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/src/auth/service.py", line 29, in login
    result = await db.execute(select(User).filter_by(email=email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 197, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 937, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/Users/timur/Desktop/Личные проекты/Audio-FastAPI/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1128, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 5432, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 5432)
INFO | app.auth | 2025-03-30 15:22:30 | line 36 | Success login for user@example.com
INFO | uvicorn.access | 2025-03-30 15:22:30 | line 477 | 127.0.0.1:52134 - "POST /auth/login HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 15:22:34 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 15:22:34 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 15:22:34 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 15:22:34 | line 92 | Finished server process [20385]
INFO | uvicorn.error | 2025-03-30 15:35:01 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 15:35:04 | line 477 | 127.0.0.1:53100 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 15:35:04 | line 477 | 127.0.0.1:53100 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 15:35:09 | line 477 | 127.0.0.1:53118 - "GET /auth/auth/yandex HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 15:37:54 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 15:37:54 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 15:37:54 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 15:37:54 | line 92 | Finished server process [21194]
INFO | uvicorn.error | 2025-03-30 15:47:28 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 15:47:33 | line 477 | 127.0.0.1:53875 - "GET /auth/auth/yandex HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 15:55:30 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 15:55:30 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 15:55:30 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 15:55:30 | line 92 | Finished server process [21892]
INFO | uvicorn.error | 2025-03-30 15:55:30 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 15:55:34 | line 477 | 127.0.0.1:54327 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 15:55:34 | line 477 | 127.0.0.1:54327 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 15:55:38 | line 477 | 127.0.0.1:54336 - "GET /auth/auth/yandex HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 15:56:26 | line 477 | 127.0.0.1:54393 - "GET /auth/auth/yandex HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 15:57:12 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 15:57:12 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 15:57:12 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 15:57:12 | line 92 | Finished server process [22305]
INFO | uvicorn.error | 2025-03-30 15:57:12 | line 62 | Application startup complete.
INFO | uvicorn.error | 2025-03-30 15:57:15 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 15:57:15 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 15:57:15 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 15:57:15 | line 92 | Finished server process [22411]
INFO | uvicorn.error | 2025-03-30 16:10:34 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 16:10:37 | line 477 | 127.0.0.1:54945 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:10:37 | line 477 | 127.0.0.1:54945 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:10:41 | line 477 | 127.0.0.1:54957 - "GET /auth/auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:10:42 | line 477 | 127.0.0.1:54957 - "GET /auth/auth/login HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 16:12:03 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 16:12:03 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 16:12:03 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 16:12:03 | line 92 | Finished server process [23183]
INFO | uvicorn.error | 2025-03-30 16:23:37 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 16:23:40 | line 477 | 127.0.0.1:55400 - "GET /auth/auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:23:47 | line 477 | 127.0.0.1:55409 - "GET /auth/callback?code=ugj5v2rfknz527lx&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 404
INFO | uvicorn.error | 2025-03-30 16:27:04 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 16:27:04 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 16:27:04 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 16:27:04 | line 92 | Finished server process [24005]
INFO | uvicorn.error | 2025-03-30 16:27:04 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 16:27:15 | line 477 | 127.0.0.1:55549 - "GET /auth/callback?code=q6nz6w6wv4zumnzp&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 404
INFO | uvicorn.error | 2025-03-30 16:27:30 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 16:27:30 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 16:27:30 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 16:27:30 | line 92 | Finished server process [24188]
INFO | uvicorn.error | 2025-03-30 16:27:31 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 16:27:36 | line 477 | 127.0.0.1:55573 - "GET /auth/auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:27:40 | line 477 | 127.0.0.1:55576 - "GET /auth/callback?code=qrgk6qelyfkbals7&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 404
INFO | uvicorn.error | 2025-03-30 16:28:19 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 16:28:20 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 16:28:20 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 16:28:20 | line 92 | Finished server process [24230]
INFO | uvicorn.error | 2025-03-30 16:28:20 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 16:28:27 | line 477 | 127.0.0.1:55632 - "GET /auth/callback?code=luup6gesoqyte4z6&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 307
INFO | uvicorn.access | 2025-03-30 16:28:29 | line 477 | 127.0.0.1:55632 - "GET /auth/callback/?code=luup6gesoqyte4z6&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 16:29:30 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 16:29:30 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 16:29:30 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 16:29:30 | line 92 | Finished server process [24286]
INFO | uvicorn.error | 2025-03-30 16:29:38 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 16:29:40 | line 477 | 127.0.0.1:55675 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:29:40 | line 477 | 127.0.0.1:55675 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:29:57 | line 477 | 127.0.0.1:55676 - "GET /auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:29:59 | line 477 | 127.0.0.1:55676 - "GET /auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 16:30:06 | line 477 | 127.0.0.1:55691 - "GET /auth/callback?code=arrgyyzu2o5lgcx2&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 307
INFO | uvicorn.access | 2025-03-30 16:30:07 | line 477 | 127.0.0.1:55691 - "GET /auth/callback/?code=arrgyyzu2o5lgcx2&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 16:39:15 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 16:39:15 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 16:39:15 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 16:39:15 | line 92 | Finished server process [24383]
INFO | uvicorn.error | 2025-03-30 17:10:19 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 17:10:22 | line 477 | 127.0.0.1:57188 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 17:10:22 | line 477 | 127.0.0.1:57188 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 17:10:27 | line 477 | 127.0.0.1:57196 - "GET /auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 17:10:35 | line 477 | 127.0.0.1:57205 - "GET /auth/callback?code=wjevr2kdj2axpqqc&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 307
INFO | app.auth | 2025-03-30 17:10:37 | line 57 | User registered successfully: mrt200228@yandex.ru
INFO | uvicorn.access | 2025-03-30 17:10:37 | line 477 | 127.0.0.1:57205 - "GET /auth/callback/?code=wjevr2kdj2axpqqc&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 17:11:15 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 17:11:15 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 17:11:15 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 17:11:15 | line 92 | Finished server process [27092]
INFO | uvicorn.error | 2025-03-30 17:11:39 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 17:11:47 | line 477 | 127.0.0.1:57317 - "GET /auth/callback?code=otlxuvphyghcr3jq&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 307
INFO | app.auth | 2025-03-30 17:11:48 | line 50 | User already exists: mrt200228@yandex.ru
INFO | uvicorn.access | 2025-03-30 17:11:48 | line 477 | 127.0.0.1:57317 - "GET /auth/callback/?code=otlxuvphyghcr3jq&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 17:12:08 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 17:12:08 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 17:12:08 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 17:12:08 | line 92 | Finished server process [27201]
INFO | uvicorn.error | 2025-03-30 17:24:41 | line 62 | Application startup complete.
INFO | uvicorn.access | 2025-03-30 17:24:45 | line 477 | 127.0.0.1:57982 - "GET /docs HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 17:24:45 | line 477 | 127.0.0.1:57982 - "GET /openapi.json HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 17:25:02 | line 477 | 127.0.0.1:57996 - "GET /auth/login HTTP/1.1" 200
INFO | uvicorn.access | 2025-03-30 17:25:10 | line 477 | 127.0.0.1:58008 - "GET /auth/callback?code=gu4xsykxqayabyq3&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 307
INFO | app.auth | 2025-03-30 17:25:12 | line 52 | User already exists: mrt200228@yandex.ru
INFO | uvicorn.access | 2025-03-30 17:25:12 | line 477 | 127.0.0.1:58008 - "GET /auth/callback/?code=gu4xsykxqayabyq3&cid=zbv0vbxwv5en85bfhu816br5jm HTTP/1.1" 200
INFO | uvicorn.error | 2025-03-30 17:25:32 | line 258 | Shutting down
INFO | uvicorn.error | 2025-03-30 17:25:32 | line 67 | Waiting for application shutdown.
INFO | uvicorn.error | 2025-03-30 17:25:32 | line 76 | Application shutdown complete.
INFO | uvicorn.error | 2025-03-30 17:25:32 | line 92 | Finished server process [27926]
